version: '3'

services:
    database:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: mytodolist
        ports:
            - '5438:5432'
        volumes: 
            - ./db:/var/lib/postgresql/data
            # - ./db-sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql            
